name: ci

on: [push, pull_request, release]

jobs:
  test:
    name: test get-aws-config on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: clone repo
        uses: actions/checkout@v1.0.0
      - name: install deno
        uses: denolib/setup-deno@v1.1.0
      - name: run tests
        run: pwd && ls && deno run --allow-env --allow-read ./test.ts